"""Package the desktop app into a single Windows ``.exe``.

    python local_agent_setup.py build-desktop      # or
    persian-local-installer

Steps performed:

1. Render the application icon to ``build/desktop/icon.ico``.
2. Write a PyInstaller spec that bundles the web UI (templates, CSS, JS,
   vendored libraries and fonts) as data files.
3. Run PyInstaller in one-file, windowed mode.
4. Optionally run Inno Setup (``iscc``) to produce an installer.

The generated ``.exe`` needs no Python on the target machine and uses
the Edge WebView2 runtime that ships with Windows 10/11.
"""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PACKAGE = ROOT / "local_agent"
BUILD_DIR = ROOT / "build" / "desktop"
DIST_DIR = ROOT / "dist"
SPEC_PATH = BUILD_DIR / "persian-local-assistant.spec"
ICON_PATH = BUILD_DIR / "icon.ico"
EXE_NAME = "PersianLocalAssistant"

#: Modules PyInstaller's static analysis cannot see (imported lazily).
HIDDEN_IMPORTS = [
    "webview",
    "webview.platforms.edgechromium",
    "webview.platforms.winforms",
    "clr_loader",
    "pythonnet",
    "pystray",
    "pystray._win32",
    "PIL",
    "PIL.Image",
    "PIL.ImageDraw",
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan.on",
    "fastapi",
    "pydantic",
    "pydantic.deprecated.decorator",
    "local_agent.desktop.app",
    "local_agent.web.app",
    "local_agent.bridge.server.server",
]

EXCLUDES = ["tkinter", "matplotlib", "numpy", "pytest", "playwright", "telethon"]


# ---------------------------------------------------------------------------
# Spec generation
# ---------------------------------------------------------------------------


def render_icon(path: Path = ICON_PATH) -> Path | None:
    """Draw the .ico used by the exe, the window and the installer."""
    try:
        from .tray import save_icon

        path.parent.mkdir(parents=True, exist_ok=True)
        return save_icon(path)
    except Exception as exc:  # noqa: BLE001
        print(f"!! could not render the icon ({exc}); building without one")
        return None


def web_datas() -> list[tuple[str, str]]:
    """(source, destination) pairs for every front-end asset."""
    web = PACKAGE / "web"
    pairs: list[tuple[str, str]] = []
    for folder in ("templates", "static"):
        source = web / folder
        if source.is_dir():
            pairs.append((str(source), f"local_agent/web/{folder}"))
    return pairs


def build_spec(*, icon: Path | None, onefile: bool = True, console: bool = False) -> str:
    """Return the text of the PyInstaller spec file."""
    datas = ",\n        ".join(f"({src!r}, {dst!r})" for src, dst in web_datas())
    hidden = ",\n        ".join(repr(name) for name in HIDDEN_IMPORTS)
    excludes = ",\n        ".join(repr(name) for name in EXCLUDES)
    icon_line = f"icon={str(icon)!r}," if icon else ""
    entry = str(PACKAGE / "desktop" / "launcher.py")

    exe_block = (
        f"""exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name={EXE_NAME!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    runtime_tmpdir=None,
    console={console!r},
    disable_windowed_traceback=False,
    {icon_line}
)"""
        if onefile
        else f"""exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name={EXE_NAME!r},
    debug=False,
    strip=False,
    upx=True,
    console={console!r},
    {icon_line}
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    name={EXE_NAME!r},
)"""
    )

    return f"""# -*- mode: python ; coding: utf-8 -*-
# Generated by local_agent/desktop/build.py — do not edit by hand.

block_cipher = None

a = Analysis(
    [{entry!r}],
    pathex=[{str(ROOT)!r}],
    binaries=[],
    datas=[
        {datas}
    ],
    hiddenimports=[
        {hidden}
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=[
        {excludes}
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

{exe_block}
"""


def write_spec(path: Path = SPEC_PATH, **kwargs) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_spec(**kwargs), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Build steps
# ---------------------------------------------------------------------------


def ensure_pyinstaller() -> bool:
    try:
        import PyInstaller  # noqa: F401

        return True
    except ImportError:
        print("PyInstaller is not installed. Install it with:")
        print("    pip install pyinstaller")
        return False


def run_pyinstaller(spec: Path, *, clean: bool = True) -> int:
    command = [sys.executable, "-m", "PyInstaller", str(spec), "--noconfirm"]
    if clean:
        command.append("--clean")
    command += ["--distpath", str(DIST_DIR), "--workpath", str(BUILD_DIR / "work")]
    print("$ " + " ".join(command))
    return subprocess.call(command, cwd=str(ROOT))


def find_iscc() -> str | None:
    """Locate the Inno Setup compiler."""
    found = shutil.which("iscc") or shutil.which("ISCC")
    if found:
        return found
    for base in (
        r"C:\Program Files (x86)\Inno Setup 6",
        r"C:\Program Files\Inno Setup 6",
    ):
        candidate = Path(base) / "ISCC.exe"
        if candidate.is_file():
            return str(candidate)
    return None


def run_inno(script: Path | None = None) -> int:
    """Compile the Inno Setup installer.  Returns a shell-style exit code."""
    iscc = find_iscc()
    if iscc is None:
        print("!! Inno Setup (iscc.exe) not found — skipping the installer.")
        print("   Download it from https://jrsoftware.org/isdl.php")
        return 0
    target = script or (Path(__file__).resolve().parent / "installer.iss")
    command = [iscc, str(target)]
    print("$ " + " ".join(command))
    return subprocess.call(command, cwd=str(ROOT))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="persian-local-installer",
        description="Build the Windows desktop app with PyInstaller.",
    )
    parser.add_argument("--onedir", action="store_true", help="build a folder instead of one file")
    parser.add_argument("--console", action="store_true", help="keep the console window (debugging)")
    parser.add_argument("--spec-only", action="store_true", help="write the .spec and stop")
    parser.add_argument("--installer", action="store_true", help="also run Inno Setup afterwards")
    parser.add_argument("--no-clean", action="store_true", help="reuse the previous build cache")
    args = parser.parse_args(argv if argv is not None else sys.argv[1:])

    if sys.platform != "win32":
        print("!! You are not on Windows: the produced binary will not be a .exe.")
        print("   Run this on Windows 10/11 to build the real desktop app.\n")

    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    icon = render_icon()
    spec = write_spec(icon=icon, onefile=not args.onedir, console=args.console)
    print(f"spec written: {spec}")
    if args.spec_only:
        return 0

    if not ensure_pyinstaller():
        return 1
    code = run_pyinstaller(spec, clean=not args.no_clean)
    if code != 0:
        print("!! PyInstaller failed")
        return code

    exe = DIST_DIR / (f"{EXE_NAME}.exe" if sys.platform == "win32" else EXE_NAME)
    if exe.exists():
        size_mb = exe.stat().st_size / (1024 * 1024)
        print(f"\n✅ built {exe}  ({size_mb:.1f} MB)")
    else:
        print(f"\n✅ build finished — see {DIST_DIR}")

    if args.installer:
        return run_inno()
    print("\nTo build the Windows installer as well:")
    print("    python local_agent_setup.py build-desktop --installer")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
