"""Shared platform helpers."""

from .platform import (
    Platform,
    capabilities,
    current_platform,
    has_display,
    is_container,
    is_headless_server,
    is_linux,
    is_macos,
    is_windows,
    is_wsl,
    list_installed_apps_windows,
    log_platform_summary,
    move_resize_window,
    minimize_window,
    maximize_window,
    resolve_windows_executable,
    start_windows_process,
    iter_windows_windows,
    windows_desktop_session,
)

__all__ = [
    "Platform",
    "capabilities",
    "current_platform",
    "has_display",
    "is_container",
    "is_headless_server",
    "is_linux",
    "is_macos",
    "is_windows",
    "is_wsl",
    "list_installed_apps_windows",
    "log_platform_summary",
    "move_resize_window",
    "minimize_window",
    "maximize_window",
    "resolve_windows_executable",
    "start_windows_process",
    "iter_windows_windows",
    "windows_desktop_session",
]
